cabal-version: 3.0
name: sss2026
version: 0.1.0.0
license: MIT
author: James Santucci
maintainer: james.santucci@gmail.com
build-type: Simple

common warnings
  ghc-options: -Wall

library
  import: warnings
  build-depends:
    base,
    hgg-core == 0.1.0.0,
    hgg-svg == 0.1.0.0,
    monad-bayes >= 1.3 && < 2,
    random >= 1.2 && <3,
    text >= 2.1 && < 3,
    vector >= 0.13 && < 0.14

  hs-source-dirs: src
  default-language: Haskell2010
  -- cabal-gild: discover src
  exposed-modules:
    DebuggingTime
