cabal-version: 3.0
name: example
version: 0.1.0.0
license: MIT
author: James Santucci
maintainer: james.santucci@umbra.com
build-type: Simple

common warnings
  ghc-options: -Wall

library sss2026
  import: warnings
  build-depends:
    base,
    monad-bayes,
    random,

  hs-source-dirs: src
  default-language: Haskell2010
  -- cabal-gild: discover src
  exposed-modules:
    DebuggingTime
