#! /usr/bin/env bash

set -e

function usage() {
    echo -n \
"Usage: $(basename "$0")

Format source, test, and project definition files
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        echo "Formatting cabal file"
        cabal-gild -i sss2026.cabal \
                   -o sss2026.cabal

        echo "Formatting nix files"
        nixfmt flake.nix

        echo "Formatting source files"
        find ./src -name "*.hs" | xargs ormolu -i

        echo "Formatting elm files"
        elm-format --yes fe/
    fi
fi
